# Seed plants table here
# Seed garden_plants table here

CREATE TABLE plants (
    id INT UNSIGNED AUTO_INCREMENT,
    plant_name VARCHAR(50),
    zone VARCHAR(50),
    PRIMARY KEY (id)
);

# Finish this

INSERT INTO plants (plant_name, zone)
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2'),
VALUES ('value1', 'value2');